use_frameworks!

target 'MJXAppUpdater_Example' do
  pod 'MJXAppUpdater', :path => '../'

  target 'MJXAppUpdater_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
